# version: "3"
# services:
#   web:
#     build: .
#     ports:
#       - "8888:80"

#   ngrok:
#     image: ngrok/ngrok
#     restart: unless-stopped
#     environment:
#       - NGROK_AUTHTOKEN=2lHCOnVSUQmLpkJeXZEh2Q0CHE2_6AhjxeQA5QB6UNe3qvA8H
#     command: http web:80

version: "3"

services:
  web:
    build: .
    container_name: my-nginx
    ports:
      - "8080:80"

